name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ezchang/ezramchang:$(git rev-parse HEAD)
    - name: Publish the Docker image
      run: docker push ezchang/ezramchang
    - name: Set permissions on SSH files
      run: chmod 600 ~/.ssh/id_rsa
    - name: Copy private key
      run: echo ${{ secrets.PRIVATE_KEY }} > ~/.ssh/id_rsa
    - name: Test SSH
      run: ssh ${{ secrets.USER }}@${{ secrets.HOST }} 'ls -la'
